name: aura_flutter
description: A new Flutter project for Aura Smart Home.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  supabase_flutter: ^2.3.1
  go_router: ^13.0.0
  lucide_icons: ^0.257.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  serverpod_client: ^2.3.0
  serverpod_flutter: ^2.3.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
